import { ThemeProvider } from "@/components/main-header/theme-provider";
import MainHeader from "@/components/main-header/main-header";
import type { Metadata } from "next";
import "./globals.css";

import MainHeaderBackground from "@/components/main-header/main-header-background";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-slate-100 dark:bg-slate-800">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainHeaderBackground />

          <MainHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
